version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mecmanager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Quan@762003
      MYSQL_DATABASE: vaccine_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
